name: Fetch manifests
description: Downloads and unzips all build manifest artifacts for the current workflow run.
author: Snapcrafters
branding:
  icon: code
  color: orange

inputs:
  token:
    description: "A token with permissions to get artifacts from this repository"
    required: true

runs:
  using: composite
  steps:
    # This is a temporary fix for when we're using the Canonical hosted runners and tools aren't
    # available by default. Can be removed once the ticket is closed.
    - name: Ensure `gh` tool is installed
      shell: bash
      run: |
        if ! command -v gh; then
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh
        fi
        if ! command -v unzip; then
          sudo apt-get update
          sudo apt-get install -y unzip
        fi
    - name: Fetch artifacts
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        # Construct the URL for the API endpoint where the artifacts are available
        url="/repos/${{ github.repository }}/actions/runs/${GITHUB_RUN_ID}/artifacts"

        # Get a list of IDs for appropriately named artifacts (those starting 'manifest-*')
        artifacts="$(gh api "$url" --jq '.artifacts[] | select(.name | startswith("manifest-")) | .id')"

        # Iterate over the manifest URLS, downloading and unpacking them one by one
        for id in $artifacts; do
          gh api "/repos/${{ github.repository }}/actions/artifacts/${id}/zip" > manifests.zip
          unzip manifests.zip
        done
